servo_node:
  ros__parameters:
    moveit_servo:
      use_gazebo: false

      status_topic: /servo_node/status
      command_in_type: "speed_units"

      scale:
        linear: 1.0
        rotational: 1.0
        joint: 1.0

      incoming_command_timeout: 0.3
      num_outgoing_halt_msgs_to_publish: 10

      publish_period: 0.02
      low_latency_mode: false

      move_group_name: robot_arm_group

      planning_frame: base_link
      ee_frame_name: eeflink
      robot_link_command_frame: eeflink

      joint_topic: /joint_states

      command_out_topic: /robot_arm_group_controller/joint_trajectory
      command_out_type: trajectory_msgs/JointTrajectory

      publish_joint_positions: true
      publish_joint_velocities: false
      publish_joint_accelerations: false

      joint_limit_margin: 0.02

      lower_singularity_threshold: 17.0
      hard_stop_singularity_threshold: 30.0
      leaving_singularity_threshold_multiplier: 2.0

      cartesian_command_in_topic: /servo_node/delta_twist_cmds
      joint_command_in_topic: /servo_node/delta_joint_cmds

      check_collisions: false
      collision_check_rate: 10.0
      self_collision_proximity_threshold: 0.05
      scene_collision_proximity_threshold: 0.05
